### PR TITLE
docs: fix link for `RemoveBarriers` pass, update docs build scripts

### LINKED ISSUE #444: Flaky links in pytket-qiskit docs index page
As of today the links in this table -> https://docs.quantinuum.com/tket/extensions/pytket-qiskit/#default-compilation go to the API docs page for `pytket.passes` but not the relevant subsection for the specific pass.

Also the entry for `RemoveBarriers` in the `optimisation_level=3` column is missing.

### PR DESCRIPTION
**Pull request by CalMacCQ**
# Description

1.  Picking up the docs link fix from https://github.com/CQCL/pytket-qiskit/pull/443 so we don't have to wait for the docs build in C.I. to be fixed.
2. Update docs theming submodule
3. update the docs build script to replace all `_tket` links for the passes in the default compilation table

Only (1.) affects the website. Everything else is just for the docs build in pytket-qiskit. This is still broken. See #458 

Drive by: black format the `qiskit_convert.py` file after a `black` package update.

closes #444

### CODE REVIEW

File: docs/build-docs.sh [hunk 1]
```diff
@@ -15,6 +15,14 @@ sed -i '' 's#CQCL/tket#CQCL/'$EXTENSION_NAME'#' _static/nav-config.js
 # Build the docs. Ensure we have the correct project title.
 sphinx-build -b html -D html_title="$EXTENSION_NAME" . build 
 
+if [[ "$OSTYPE" == "darwin"* ]]; then
```
Comment (CalMacCQ) [inline docs/build-docs.sh:18]: This is to replace all the _tket links in the (LOCAL) docs build

File: docs/index.md [hunk 2]
```diff
@@ -208,7 +208,7 @@ Every {py:class}`~pytket.backends.backend.Backend` in pytket has its own {py:met
 * - [AutoRebase [2]](inv:#*.AutoRebase)
   - [SynthesiseTket](inv:#*.SynthesiseTket)
   - [FullPeepholeOptimise](inv:#*.passes.FullPeepholeOptimise)
-  - [RemoveBarriers](inv:#*pytket.passes.RemoveBarriers)
+  - [RemoveBarriers](inv:#*pytket._tket.passes.RemoveBarriers)
```
Comment (CalMacCQ) [inline docs/index.md:211]: This seems weird but I've verified that this works in the built html. The _tket line is replaced so there is no danger of broken links.

**Review by cqc-alec — APPROVED** [review]
